In [2]:
import numpy as np

In [10]:
# 初始化一个两个元素的一维数组
arr1 = np.arange(2)
print("一维数组:\n", arr1)

# 初始化一个4个元素的一维数组，并修改为 2x2 的二维数组
arr2 = np.arange(4).reshape(2,2)
print("二维数组:\n", arr2)

# 初始化一个8个元素的一维数组，并修改为 2x2x2 的三维数组
arr3 = np.arange(8).reshape(2,2,2)
print("三维数组:\n", arr3)

# 打印出三个数组的类型
print(type(arr1), type(arr2), type(arr3))



一维数组:
 [0 1]
二维数组:
 [[0 1]
 [2 3]]
三维数组:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [12]:
a = [1,3,5,7]
arr = np.array(a)
print(arr, type(arr))

[1 3 5 7] <class 'numpy.ndarray'>


In [13]:
arr1 = np.arange(10)
print(arr1, type(arr1))

arr2 = np.arange()

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [17]:
# 将 10 个元素的 arr1 调整为两个五个元素的一维数组组成的二维数组
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
arr1.reshape(2,1,5)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
# 形状以列表的形式传入，[3,4] 代表 3x4 的二维数组
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
print("一维数组：\n", np.ones(3))
print("二维数组：\n", np.ones([3,4]))

一维数组：
 [1. 1. 1.]
二维数组：
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
# 生成 20 个 0到1之间的随机数
print(np.random.rand(20))

# 生成 20 个 0 到10 之间的随机数
print(np.random.randint(0,10,20))

[0.4041234  0.54505458 0.78659903 0.81566742 0.19598521 0.66532724
 0.35192288 0.83556087 0.90010909 0.24167259 0.20850511 0.93573772
 0.51754404 0.98113317 0.9792484  0.74293827 0.64741681 0.29030238
 0.81008087 0.15342404]
[1 5 9 7 5 1 7 2 0 1 8 2 8 1 1 3 4 5 3 5]


In [42]:
print("2x2 的单位矩阵：\n",np.identity(2))
print("3x3 的单位矩阵：\n", np.identity(3))

2x2 的单位矩阵：
 [[1. 0.]
 [0. 1.]]
3x3 的单位矩阵：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
import csv

In [3]:
arr = np.ones([3,4])

print("维度数：", arr.ndim)
print("形状：", arr.shape)
print("元素数：", arr.size)


维度数： 2
形状： (3, 4)
元素数： 12


In [4]:
from bs4 import BeautifulSoup

In [5]:
import bs4

In [11]:
arr = np.arange(12)
print("arr：",arr)
print("第二个元素：",arr[1])
print("第十一个元素：",arr[10])

arr： [ 0  1  2  3  4  5  6  7  8  9 10 11]
第二个元素： 1
第十一个元素： 10


In [16]:
# 二维数组索引
arr0 = np.arange(12).reshape(3,4)
print("arr0：\n", arr0)
print("第一维第三个，第二维第四个元素：", arr0[2,3])

# 打印空行
print("\n")

# 三维数组索引
arr1 = np.arange(12).reshape(2,2,3)
print("arr1：", arr1)
print("第一维第二个，第二维第一个，第三维第三个数：", arr1[1,0,2])

arr0：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
第一维第三个，第二维第四个元素： 11


arr1： [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
第一维第二个，第二维第一个，第三维第三个数： 8


In [18]:
arr = np.arange(10)
print("arr：\n", arr)
print("从索引2到索引4：",arr[2:4])
print("从索引1到索引5：", arr[1:5])



arr：
 [0 1 2 3 4 5 6 7 8 9]
从索引2到索引4： [2 3]
从索引1到索引5： [1 2 3 4]


In [21]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[1:3,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3, 6])

In [4]:
arr = np.arange(12).reshape(2,6)
print("原始二维数组：\n",arr)
print("提供一个索引后，得到一维数组：\n", arr[0])

原始二维数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
提供一个索引后，得到一维数组：
 [0 1 2 3 4 5]


In [8]:
arr = np.arange(12).reshape(3,4)
print("原始数组：\n", arr)

print("数组+2 ：\n", arr+2)

print("数组*3 ：\n", arr*3)

print("数组/5：\n", arr / 5)

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组+2 ：
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
数组*3 ：
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
数组/5：
 [[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]
 [1.6 1.8 2.  2.2]]


In [21]:
arr = np.arange(12).reshape(3,4)
arr1 = np.random.randint(1,20, [3,4])
print("原始数组1：\n", arr)
print("原始数组2：\n", arr1)
print("数组相加的结果：\n", arr + arr1)
print("数组相乘的结果：\n", arr * arr1)


原始数组1：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原始数组2：
 [[ 6  8  8  2]
 [ 4 11 15  1]
 [19 10  5 13]]
数组相加的结果：
 [[ 6  9 10  5]
 [ 8 16 21  8]
 [27 19 15 24]]
数组相乘的结果：
 [[  0   8  16   6]
 [ 16  55  90   7]
 [152  90  50 143]]


In [22]:
arr = np.arange(12).reshape(3,4)
arr1 = np.arange(4)
print("原始数组1：\n", arr)
print("原始数组2：\n", arr1)
print("数组相加的结果：\n", arr + arr1)
print("数组相乘的结果：\n", arr * arr1)

原始数组1：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原始数组2：
 [0 1 2 3]
数组相加的结果：
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
数组相乘的结果：
 [[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [24]:
arr = np.arange(12).reshape(3,4)
print("原始数组：\n", arr)
print("求平方：\n", np.square(arr))
print("开根：\n", np.sqrt(arr))
print("正弦函数：\n", np.sin(arr))

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
求平方：
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
开根：
 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
正弦函数：
 [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [30]:
arr = np.arange(4)
arr1 = np.arange(2,6)
print("数组1：", arr)
print("数组2：", arr1)

print("不允许误差：", np.allclose(arr, arr1))
print("允许误差1：", np.allclose(arr, arr1, atol=1))
print("允许误差2：", np.allclose(arr, arr1, atol=2))


数组1： [0 1 2 3]
数组2： [2 3 4 5]
不允许误差： False
允许误差1： False
允许误差2： True


In [33]:
np.random.randint(90,150, 5)

array([ 94, 135,  92, 104, 149])

In [35]:
a = [100, 122, 123,  94, 147]
b = [ 94, 120,  131, 103, 140]

arr_a = np.array(a)
arr_b = np.array(b)

arr_a = arr_a * 100 / 150
arr_b = arr_b * 100 / 150

print("小A百分制成绩", arr_a)
print("小B百分制成绩", arr_b)

print("小A和小B水平是否接近：", np.allclose(arr_a, arr_b, atol=10))

小A百分制成绩 [66.66666667 81.33333333 82.         62.66666667 98.        ]
小B百分制成绩 [62.66666667 80.         87.33333333 68.66666667 93.33333333]
小A和小B水平是否接近： True
